name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Updated to Node 20 per Vite requirement
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt
    
    - name: Install Node dependencies
      run: npm install
    
    - name: Check TypeScript
      run: npm run build
    
    - name: Check Rust formatting
      run: cd src-tauri && cargo fmt --all -- --check

  build-artifacts:
    runs-on: ${{ matrix.os }}
    needs: lint
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Install system dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-22.04'
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          gdal-bin libgdal-dev \
          build-essential pkg-config libssl-dev \
          libwebkit2gtk-4.0-dev \
          libjavascriptcoregtk-4.0-dev \
          libgtk-3-dev \
          libayatana-appindicator3-dev \
          librsvg2-dev \
          libsoup2.4-dev
    
    - name: Install system dependencies (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install gdal pkg-config
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'  # Updated to Node 20
        cache: 'npm'
    
    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install Node dependencies
      run: npm install
    
    - name: Build application
      run: npm run tauri build
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: shadow-calculator-${{ matrix.os }}
        path: |
          src-tauri/target/release/bundle/
        retention-days: 30